version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin       # Default PostgreSQL username
      POSTGRES_PASSWORD: admin   # Default PostgreSQL password
      POSTGRES_DB: tgbot          # Default database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Default email for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin        # Default password for pgAdmin
    ports:
      - "5050:80"
    networks:
      - postgres_network

volumes:
  postgres_data: # Volume for PostgreSQL data persistence

networks:
  postgres_network: